# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grading.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrading.proto\">\n\x0eGradingRequest\x12\x13\n\x0bguest_email\x18\x01 \x01(\t\x12\x17\n\x0f\x65xam_content_id\x18\x02 \x01(\x03\"\x8d\x01\n\x0fGradingResponse\x12\x41\n\x11\x63osine_similarity\x18\x01 \x03(\x0b\x32&.GradingResponse.CosineSimilarityEntry\x1a\x37\n\x15\x43osineSimilarityEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\x36\n\x06Grader\x12,\n\x05grade\x12\x0f.GradingRequest\x1a\x10.GradingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADINGRESPONSE_COSINESIMILARITYENTRY']._loaded_options = None
  _globals['_GRADINGRESPONSE_COSINESIMILARITYENTRY']._serialized_options = b'8\001'
  _globals['_GRADINGREQUEST']._serialized_start=17
  _globals['_GRADINGREQUEST']._serialized_end=79
  _globals['_GRADINGRESPONSE']._serialized_start=82
  _globals['_GRADINGRESPONSE']._serialized_end=223
  _globals['_GRADINGRESPONSE_COSINESIMILARITYENTRY']._serialized_start=168
  _globals['_GRADINGRESPONSE_COSINESIMILARITYENTRY']._serialized_end=223
  _globals['_GRADER']._serialized_start=225
  _globals['_GRADER']._serialized_end=279
# @@protoc_insertion_point(module_scope)
