# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grader_pb2 as grader__pb2


class GraderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.grade = channel.unary_unary(
                '/Grader/grade',
                request_serializer=grader__pb2.GradingRequest.SerializeToString,
                response_deserializer=grader__pb2.GradingResponse.FromString,
                )


class GraderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def grade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'grade': grpc.unary_unary_rpc_method_handler(
                    servicer.grade,
                    request_deserializer=grader__pb2.GradingRequest.FromString,
                    response_serializer=grader__pb2.GradingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Grader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Grader(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def grade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Grader/grade',
            grader__pb2.GradingRequest.SerializeToString,
            grader__pb2.GradingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
